const path = require("path");

// Add server's node_modules to module search path
module.paths.unshift(path.join(__dirname, "../server/node_modules"));

const mongoose = require("mongoose");
const dotenv = require("dotenv");

// Load env from server directory
dotenv.config({ path: path.join(__dirname, "../server/.env") });

// Need to require the model AFTER mongoose is set up
const Job = require("../server/models/jobModel");

const sampleJobs = [
  {
    title: "Frontend Developer",
    company: "TCS",
    location: "Bangalore",
    jobType: "hybrid",
    experienceMin: 1,
    experienceMax: 3,
    salaryMin: 5,
    salaryMax: 10,
    skills: ["react", "javascript", "css", "html"],
    description: "Build modern web applications using React.",
    platform: "linkedin",
    applicationUrl: "https://linkedin.com/jobs/1",
    easyApply: true,
    postedDate: new Date("2026-02-08"),
  },
  {
    title: "Backend Developer",
    company: "Infosys",
    location: "Hyderabad",
    jobType: "onsite",
    experienceMin: 2,
    experienceMax: 5,
    salaryMin: 8,
    salaryMax: 15,
    skills: ["node.js", "express", "mongodb", "javascript"],
    description: "Develop REST APIs and microservices.",
    platform: "naukri",
    applicationUrl: "https://naukri.com/jobs/2",
    easyApply: false,
    postedDate: new Date("2026-02-07"),
  },
  {
    title: "Full Stack Developer",
    company: "Wipro",
    location: "Pune",
    jobType: "remote",
    experienceMin: 3,
    experienceMax: 6,
    salaryMin: 12,
    salaryMax: 22,
    skills: ["react", "node.js", "mongodb", "typescript"],
    description: "End-to-end web application development.",
    platform: "indeed",
    applicationUrl: "https://indeed.com/jobs/3",
    easyApply: true,
    postedDate: new Date("2026-02-06"),
  },
  {
    title: "React Developer",
    company: "Accenture",
    location: "Mumbai",
    jobType: "hybrid",
    experienceMin: 1,
    experienceMax: 4,
    salaryMin: 6,
    salaryMax: 12,
    skills: ["react", "redux", "javascript", "tailwindcss"],
    description: "Build responsive UIs with React and Redux.",
    platform: "linkedin",
    applicationUrl: "https://linkedin.com/jobs/4",
    easyApply: true,
    postedDate: new Date("2026-02-09"),
  },
  {
    title: "Node.js Developer",
    company: "HCL",
    location: "Noida",
    jobType: "onsite",
    experienceMin: 2,
    experienceMax: 4,
    salaryMin: 7,
    salaryMax: 14,
    skills: ["node.js", "express", "postgresql", "docker"],
    description: "Build scalable backend services.",
    platform: "naukri",
    applicationUrl: "https://naukri.com/jobs/5",
    easyApply: false,
    postedDate: new Date("2026-02-05"),
  },
  {
    title: "MERN Stack Developer",
    company: "Cognizant",
    location: "Chennai",
    jobType: "remote",
    experienceMin: 2,
    experienceMax: 5,
    salaryMin: 10,
    salaryMax: 18,
    skills: ["mongodb", "express", "react", "node.js"],
    description: "Full stack development using MERN stack.",
    platform: "linkedin",
    applicationUrl: "https://linkedin.com/jobs/6",
    easyApply: true,
    postedDate: new Date("2026-02-08"),
  },
  {
    title: "Software Engineer",
    company: "Google",
    location: "Bangalore",
    jobType: "hybrid",
    experienceMin: 3,
    experienceMax: 7,
    salaryMin: 25,
    salaryMax: 50,
    skills: ["python", "java", "algorithms", "system design"],
    description: "Work on large-scale distributed systems.",
    platform: "linkedin",
    applicationUrl: "https://linkedin.com/jobs/7",
    easyApply: false,
    postedDate: new Date("2026-02-09"),
  },
  {
    title: "DevOps Engineer",
    company: "Amazon",
    location: "Hyderabad",
    jobType: "onsite",
    experienceMin: 3,
    experienceMax: 6,
    salaryMin: 20,
    salaryMax: 40,
    skills: ["aws", "docker", "kubernetes", "terraform", "ci/cd"],
    description: "Manage cloud infrastructure and CI/CD pipelines.",
    platform: "naukri",
    applicationUrl: "https://naukri.com/jobs/8",
    easyApply: false,
    postedDate: new Date("2026-02-07"),
  },
  {
    title: "Python Developer",
    company: "Flipkart",
    location: "Bangalore",
    jobType: "remote",
    experienceMin: 1,
    experienceMax: 3,
    salaryMin: 8,
    salaryMax: 16,
    skills: ["python", "django", "rest api", "postgresql"],
    description: "Build backend APIs using Python and Django.",
    platform: "indeed",
    applicationUrl: "https://indeed.com/jobs/9",
    easyApply: true,
    postedDate: new Date("2026-02-08"),
  },
  {
    title: "UI/UX Developer",
    company: "Razorpay",
    location: "Bangalore",
    jobType: "hybrid",
    experienceMin: 2,
    experienceMax: 5,
    salaryMin: 12,
    salaryMax: 20,
    skills: ["react", "figma", "css", "javascript", "design systems"],
    description: "Create beautiful and accessible user interfaces.",
    platform: "linkedin",
    applicationUrl: "https://linkedin.com/jobs/10",
    easyApply: true,
    postedDate: new Date("2026-02-09"),
  },
  // --- 10 more jobs ---
  {
    title: "Angular Developer",
    company: "Tech Mahindra",
    location: "Pune",
    jobType: "onsite",
    experienceMin: 2,
    experienceMax: 4,
    salaryMin: 7,
    salaryMax: 13,
    skills: ["angular", "typescript", "rxjs", "css"],
    description: "Develop enterprise apps with Angular.",
    platform: "naukri",
    applicationUrl: "https://naukri.com/jobs/11",
    easyApply: false,
    postedDate: new Date("2026-02-06"),
  },
  {
    title: "Data Engineer",
    company: "Microsoft",
    location: "Hyderabad",
    jobType: "hybrid",
    experienceMin: 3,
    experienceMax: 6,
    salaryMin: 20,
    salaryMax: 35,
    skills: ["python", "spark", "sql", "azure", "data pipelines"],
    description: "Build and maintain data pipelines at scale.",
    platform: "linkedin",
    applicationUrl: "https://linkedin.com/jobs/12",
    easyApply: false,
    postedDate: new Date("2026-02-07"),
  },
  {
    title: "Java Developer",
    company: "Capgemini",
    location: "Mumbai",
    jobType: "onsite",
    experienceMin: 2,
    experienceMax: 5,
    salaryMin: 8,
    salaryMax: 16,
    skills: ["java", "spring boot", "microservices", "sql"],
    description: "Build microservices with Spring Boot.",
    platform: "naukri",
    applicationUrl: "https://naukri.com/jobs/13",
    easyApply: true,
    postedDate: new Date("2026-02-05"),
  },
  {
    title: "Cloud Engineer",
    company: "Deloitte",
    location: "Bangalore",
    jobType: "remote",
    experienceMin: 3,
    experienceMax: 7,
    salaryMin: 15,
    salaryMax: 30,
    skills: ["aws", "gcp", "terraform", "linux", "networking"],
    description: "Design and manage cloud infrastructure.",
    platform: "indeed",
    applicationUrl: "https://indeed.com/jobs/14",
    easyApply: false,
    postedDate: new Date("2026-02-08"),
  },
  {
    title: "Mobile Developer",
    company: "PhonePe",
    location: "Bangalore",
    jobType: "hybrid",
    experienceMin: 2,
    experienceMax: 5,
    salaryMin: 14,
    salaryMax: 25,
    skills: ["react native", "javascript", "android", "ios"],
    description: "Build cross-platform mobile apps.",
    platform: "linkedin",
    applicationUrl: "https://linkedin.com/jobs/15",
    easyApply: true,
    postedDate: new Date("2026-02-09"),
  },
  {
    title: "QA Engineer",
    company: "Zoho",
    location: "Chennai",
    jobType: "onsite",
    experienceMin: 1,
    experienceMax: 3,
    salaryMin: 5,
    salaryMax: 10,
    skills: ["selenium", "javascript", "cypress", "api testing"],
    description: "Automate testing for web applications.",
    platform: "naukri",
    applicationUrl: "https://naukri.com/jobs/16",
    easyApply: false,
    postedDate: new Date("2026-02-06"),
  },
  {
    title: "ML Engineer",
    company: "Swiggy",
    location: "Bangalore",
    jobType: "remote",
    experienceMin: 3,
    experienceMax: 6,
    salaryMin: 18,
    salaryMax: 35,
    skills: ["python", "tensorflow", "pytorch", "machine learning"],
    description: "Build ML models for recommendation systems.",
    platform: "linkedin",
    applicationUrl: "https://linkedin.com/jobs/17",
    easyApply: false,
    postedDate: new Date("2026-02-08"),
  },
  {
    title: "Golang Developer",
    company: "Zerodha",
    location: "Bangalore",
    jobType: "remote",
    experienceMin: 2,
    experienceMax: 5,
    salaryMin: 15,
    salaryMax: 30,
    skills: ["golang", "microservices", "postgresql", "redis"],
    description: "Build high-performance trading systems.",
    platform: "indeed",
    applicationUrl: "https://indeed.com/jobs/18",
    easyApply: true,
    postedDate: new Date("2026-02-07"),
  },
  {
    title: "WordPress Developer",
    company: "Freelance",
    location: "Delhi",
    jobType: "remote",
    experienceMin: 0,
    experienceMax: 2,
    salaryMin: 3,
    salaryMax: 6,
    skills: ["wordpress", "php", "css", "javascript"],
    description: "Build and customize WordPress websites.",
    platform: "indeed",
    applicationUrl: "https://indeed.com/jobs/19",
    easyApply: true,
    postedDate: new Date("2026-02-09"),
  },
  {
    title: "System Administrator",
    company: "Mindtree",
    location: "Noida",
    jobType: "onsite",
    experienceMin: 3,
    experienceMax: 6,
    salaryMin: 8,
    salaryMax: 15,
    skills: ["linux", "networking", "bash", "aws", "monitoring"],
    description: "Maintain and monitor production servers.",
    platform: "naukri",
    applicationUrl: "https://naukri.com/jobs/20",
    easyApply: false,
    postedDate: new Date("2026-02-05"),
  },
];

const seedJobs = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("Connected to MongoDB");

    // Clear existing jobs
    await Job.deleteMany({});
    console.log("Cleared existing jobs");

    // Insert sample jobs
    const inserted = await Job.insertMany(sampleJobs);
    console.log(`Seeded ${inserted.length} jobs successfully!`);

    await mongoose.disconnect();
    console.log("Done.");
    process.exit(0);
  } catch (error) {
    console.error("Seed failed:", error);
    process.exit(1);
  }
};

seedJobs();
